### ISSUE TITLE
Depedency `request@2.55.*` has a reported vulnerability

### ISSUE THREAD

**Issue by fracmak** [kkamkou/node-akamai-http-api#12]
request utilizes the hawk library which has a known vulnerability: https://nodesecurity.io/advisories/77

The library was updated in request@2.59.0

https://github.com/request/request/blob/master/CHANGELOG.md#v2590-20150720

**Comment by kkamkou** [comment]
Thank you for the report. [I've updated the repo](https://github.com/kkamkou/node-akamai-http-api/releases/tag/0.5.0). Please, open a new ticket in case it won't work for you.
