### ISSUE TITLE
Depedency `request@2.27.*` has a reported vulnerability

### ISSUE THREAD

**Issue by rtorino** [kkamkou/node-akamai-http-api#2]
I have a project which will use this library. However, it is a part of our CI to check for npm packages with reported vulnerability using [nsp](https://www.npmjs.com/package/nsp) and CI fails on this library since the dependency `request@2.27.*` has a reported vulnerability. Can I create a PR to update `request` to `v2.5.0`?

**Comment by kkamkou** [comment]
Hi Raymond! Sure, please do it.

**Comment by rtorino** [comment]
Should I bump the version on my PR?
