### ISSUE TITLE
Ignore error 409

### ISSUE THREAD

**Issue by micky2be** [kkamkou/node-akamai-http-api#4]
When an error 409 happen on a mkdir, this is supposed to mean that the folder already exist.
Could we ignore this error.

Or maybe, when an error occur you could include the http code so we could manage on our side.

**Comment by kkamkou** [comment]
Hi Micky! Okay, I'll check.

**Comment by kkamkou** [comment]
@micky2be Please, read the `README.md`, the `Exceptions` section. I hope it'll help you.

**Comment by micky2be** [comment]
Seems good, thank you
